"use server";

import { query, execute, transaction, generateId } from "@/lib/db";
import { Ticket, TicketAnalysis, ChatMessage, KPI, ActivityLog, User } from "@/lib/types";
import { generateAnalysisWithOllama, getGostChatResponse } from "@/lib/ai";
import { getSession } from "@/lib/auth";
import { revalidatePath } from "next/cache";
import { logActivity } from "@/lib/audit";


export async function getTickets(): Promise<Ticket[]> {
  const q = `
    SELECT 
      t.number as id, 
      t.short_description as title, 
      t.description as description, 
      t.state as state,
      t.priority as priority,
      t.sys_class_name as sysClassName,
      t.assignment_group as team,
      t.assigned_to as assignedTo,
      t.sys_created_on as createdAt,
      t.sys_updated_on as updatedAt,
      t.opened_by as openedBy,
      t.opened_at as openedAt,
      t.closed_at as closedAt,
      t.closed_by as closedBy,
      t.business_service as businessService,
      t.close_notes as closeNotes,
      t.comments as comments,
      a.confidence_score * 100 as confidence
    FROM tickets t
    LEFT JOIN ai_analysis a ON t.number = a.incident_number
  `;
  const results = await query<any>(q);
  const data = results.map(r => ({
    ...r,
    status: (r.state?.toLowerCase() === 'closed' ? 'closed' : 
             r.state?.toLowerCase() === 'canceled' ? 'canceled' : 
             r.state?.toLowerCase() === 'validated' ? 'validated' : 
             r.state?.toLowerCase() === 'rejected' ? 'rejected' : 
             r.state?.toLowerCase() === 'analysis pending' ? 'analysis_pending' : 
             r.state?.toLowerCase() === 'sql proposed' ? 'sql_proposed' : 
             'pending'),
    aiConfidence: r.confidence,
  }));
  return JSON.parse(JSON.stringify(data));
}

export async function getTicketById(id: string): Promise<Ticket | null> {
  const q = `
    SELECT 
      number as id, 
      short_description as title, 
      description, 
      state, 
      priority, 
      sys_class_name as sysClassName,
      assignment_group as team, 
      assigned_to as assignedTo, 
      sys_created_on as createdAt, 
      sys_updated_on as updatedAt, 
      opened_by as openedBy,
      opened_at as openedAt,
      closed_at as closedAt,
      closed_by as closedBy,
      t.business_service as businessService,
      t.close_notes as closeNotes,
      t.comments as comments,
      a.confidence_score * 100 as confidence
    FROM tickets t
    LEFT JOIN ai_analysis a ON t.number = a.incident_number
    WHERE t.number = ?
  `;
  const tickets = await query<any>(q, [id]);
  if (tickets.length === 0) return null;
  const r = tickets[0];
  const data = {
    ...r,
    status: (r.state?.toLowerCase() === 'closed' ? 'closed' : 
             r.state?.toLowerCase() === 'canceled' ? 'canceled' : 
             r.state?.toLowerCase() === 'validated' ? 'validated' : 
             r.state?.toLowerCase() === 'rejected' ? 'rejected' : 
             r.state?.toLowerCase() === 'analysis pending' ? 'analysis_pending' : 
             r.state?.toLowerCase() === 'sql proposed' ? 'sql_proposed' : 
             'pending'),
    aiConfidence: r.confidence,
  };
  return JSON.parse(JSON.stringify(data));
}

export async function getAnalyses(): Promise<TicketAnalysis[]> {
  const rows = await query<any>("SELECT * FROM ai_analysis");
  const data = rows.map((r: any) => ({
    ticketId: r.incident_number,
    rootCause: r.root_cause || "Unknown",
    impactedTables: [],
    recommendation: r.resolution_steps || "",
    sqlProposal: r.suggested_sql || "",
    gostSummary: "Generated by GOST AI",
    urgency: "high"
  }));
  return JSON.parse(JSON.stringify(data));
}

export async function getConversations() {
  const rows = await query<any>("SELECT * FROM Conversations ORDER BY created_at DESC");
  return JSON.parse(JSON.stringify(rows));
}

/**
 * Returns all conversations enriched with message count and last message preview.
 * Used by the Chat History sidebar to render conversation cards.
 */
export async function getConversationsWithMeta() {
  const rows = await query<any>(`
    SELECT
      c.conversation_id AS conversationId,
      c.ticket_id       AS ticketId,
      c.user_matricule  AS userMatricule,
      c.title,
      c.created_at      AS createdAt,
      COUNT(m.id)        AS messageCount,
      (
        SELECT m2.content FROM Messages m2
        WHERE m2.conversation_id = c.conversation_id
        ORDER BY m2.created_at DESC LIMIT 1
      ) AS lastMessageContent,
      (
        SELECT m2.role FROM Messages m2
        WHERE m2.conversation_id = c.conversation_id
        ORDER BY m2.created_at DESC LIMIT 1
      ) AS lastMessageRole,
      (
        SELECT m2.created_at FROM Messages m2
        WHERE m2.conversation_id = c.conversation_id
        ORDER BY m2.created_at DESC LIMIT 1
      ) AS lastMessageAt
    FROM Conversations c
    LEFT JOIN Messages m ON m.conversation_id = c.conversation_id
    GROUP BY c.conversation_id
    ORDER BY COALESCE((
      SELECT MAX(m3.created_at) FROM Messages m3 WHERE m3.conversation_id = c.conversation_id
    ), c.created_at) DESC
  `);
  return JSON.parse(JSON.stringify(rows));
}

export async function getChatMessages(): Promise<ChatMessage[]> {
  const qStr = `
    SELECT m.id, m.conversation_id as conversationId, m.role, m.content, m.created_at as createdAt, c.ticket_id as ticketId, m.user_matricule as senderName
    FROM Messages m
    JOIN Conversations c ON m.conversation_id = c.conversation_id
  `;
  const rows = await query<any>(qStr);
  const data = rows.map((r: any) => ({
    id: r.id.toString(),
    conversationId: r.conversationId,
    ticketId: r.ticketId, // keep for UI backwards compatibility if needed
    role: r.role,
    content: r.content,
    createdAt: r.createdAt,
    senderName: r.role === 'AI' ? 'GOST AI' : r.senderName
  }));
  return JSON.parse(JSON.stringify(data));
}

export async function getKpis(): Promise<KPI[]> {
  // This is generic mock for now if kpis logic isn't heavily present in DB stats
  return [
    { id: "k1", category: "sla", label: "SLA Compliance Rate", value: 87, change: 3, changeType: "up", unit: "%", target: 95 },
    { id: "k2", category: "sla", label: "SLA Breaches", value: 4, change: -2, changeType: "down" },
    { id: "k7", category: "volume", label: "Open Tickets", value: 7 }
  ];
}

export async function getActivities(): Promise<ActivityLog[]> {
  const rows = await query<any>("SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT 50");
  const data = rows.map((r: any) => {
    let tId = "";
    let detailsMsg = "";
    try {
      const parsed = JSON.parse(r.details || "{}");
      tId = parsed.ticketId || "";
      
      if (!tId && typeof parsed.message === 'string') {
        const match = parsed.message.match(/(INC\d+)/);
        if (match) tId = match[1];
      }
    } catch(e) {}

    return {
      id: r.id.toString(),
      action: r.action,
      ticketId: tId,
      performedBy: r.user_matricule || "System",
      timestamp: r.created_at,
      details: r.details
    };
  });
  return JSON.parse(JSON.stringify(data));
}

export async function getUsers(): Promise<User[]> {
  const rows = await query<any>("SELECT * FROM users");
  return rows.map((r: any) => ({
    matricule: r.matricule,
    name: r.name,
    surname: r.prenom,
    role: r.role === "admin" ? "manager" : r.role === "it_support" ? "agent" : "reporter"
  }));
}

export async function getMenus() {
  const rows = await query<any>("SELECT * FROM menus");
  return JSON.parse(JSON.stringify(rows));
}

export async function getTransactions() {
  const rows = await query<any>("SELECT * FROM transactions");
  return JSON.parse(JSON.stringify(rows));
}

export async function getTableNames(): Promise<string[]> {
  const rows = await query<any>("SHOW TABLES");
  const dbName = process.env.DB_NAME || 'fors_simulator';
  return rows.map((r: any) => Object.values(r)[0] as string);
}

export async function getTableSchema(tableName: string) {
  const rows = await query<any>(`DESCRIBE ??`, [tableName]);
  return JSON.parse(JSON.stringify(rows));
}

export async function getTableData(tableName: string) {
  const rows = await query<any>(`SELECT * FROM ?? LIMIT 500`, [tableName]);
  return JSON.parse(JSON.stringify(rows));
}

export async function createTicket(ticket: Partial<Ticket>) {
  const q = `
    INSERT INTO tickets (
      number, 
      short_description, 
      description, 
      state, 
      priority, 
      assignment_group, 
      assigned_to, 
      sys_created_on, 
      sys_updated_on, 
      opened_by, 
      opened_at, 
      sys_class_name
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ON DUPLICATE KEY UPDATE 
      short_description = VALUES(short_description),
      description = VALUES(description),
      state = VALUES(state),
      sys_updated_on = VALUES(sys_updated_on)
  `;
  const now = new Date().toISOString().replace('T', ' ').substring(0, 19);
  const values = [
    ticket.id,
    ticket.title,
    ticket.description,
    'pending',
    ticket.priority || 'P3',
    ticket.team || 'IT Support',
    ticket.assignedTo || null,
    now,
    now,
    'Manual Entry',
    now,
    'incident'
  ];
  await query(q, values);

  // Log ticket creation
  const session = await getSession();
  await logActivity("AI_ANALYSIS_GENERATED", {
    ticketId: ticket.id,
    details: { message: `Created ticket ${ticket.id}` }
  });

  return { success: true };
}

export async function analyzeTicketAction(ticketId: string, title: string, description: string) {
  // 0. Check if ticket is already validated
  const [ticket] = await query<any>("SELECT state FROM tickets WHERE number = ?", [ticketId]);
  if (ticket && (ticket.state === 'Validated' || ticket.state?.toLowerCase() === 'validated')) {
    throw new Error("Cannot re-analyze a validated ticket.");
  }

  // 1. Check for Predefined Queries matching the problem
  const keywords = title.split(/\s+/).filter(w => w.length > 4);
  let matchingQuery: any = null;
  
  if (keywords.length > 0) {
    const qConditions = keywords.map(() => `description LIKE ?`).join(' OR ');
    const qParams = keywords.map(k => `%${k}%`);
    const rows = await query<any>(`SELECT * FROM predefined_queries WHERE isActive = 1 AND (${qConditions}) LIMIT 1`, qParams);
    if (rows && rows.length > 0) matchingQuery = rows[0];
  }

  let analysis: any;
  if (matchingQuery) {
    analysis = {
      rootCause: `Matched predefined pattern: ${matchingQuery.name}`,
      confidence: 95,
      urgency: "high",
      impactedTables: [],
      sqlProposal: matchingQuery.sql,
      recommendation: `Automated resolution via predefined query: ${matchingQuery.description}`,
      gostSummary: "Matched a known solution template. SQL extracted automatically."
    };
  } else {
    analysis = await generateAnalysisWithOllama(title, description);
  }
  
  // Generate a unique analysis_id for this analysis run
  const analysisId = generateId("ANALYSIS");

  // Save to DB
  try {
    await execute(`
      INSERT INTO ai_analysis (analysis_id, incident_number, root_cause, resolution_steps, suggested_sql, confidence_score)
      VALUES (?, ?, ?, ?, ?, ?)
      ON DUPLICATE KEY UPDATE
        analysis_id = VALUES(analysis_id),
        root_cause = VALUES(root_cause),
        resolution_steps = VALUES(resolution_steps),
        suggested_sql = VALUES(suggested_sql),
        confidence_score = VALUES(confidence_score)
    `, [
      analysisId,
      ticketId,
      analysis.rootCause,
      analysis.recommendation,
      analysis.sqlProposal,
      analysis.confidence / 100
    ]);
    
    // Save "ghost response" in ticket details with pending status
    await query("UPDATE tickets SET state = 'Analysis Pending', comments = ? WHERE number = ?", [
      `GHOST RESPONSE (PENDING): ${analysis.gostSummary}\n\nProposed Solution:\n${analysis.recommendation}`,
      ticketId
    ]);

    // Log the action
    await logActivity("AI_ANALYSIS_GENERATED", {
      ticketId,
      details: { 
        message: `Generated AI analysis for ${ticketId}`, 
        analysisId, 
        confidence: analysis.confidence,
        urgency: analysis.urgency
      }
    });

  } catch (err) {
    console.error("Failed to save analysis:", err);
  }

  return JSON.parse(JSON.stringify(analysis));
}

export async function chatWithGostAction(ticketId: string, message: string, history: any[] = []) {
  const sessionValue = await getSession();
  const userMatricule = sessionValue.user?.matricule || "UNKNOWN";
  
  // Find or create Conversation
  let conversationId = ticketId + "_conv";
  const convRows = await query<any>("SELECT conversation_id FROM Conversations WHERE ticket_id = ?", [ticketId]);
  if (convRows.length > 0) {
    conversationId = convRows[0].conversation_id;
  } else {
    await query("INSERT INTO Conversations (conversation_id, ticket_id, user_matricule) VALUES (?, ?, ?)", [conversationId, ticketId, userMatricule]);
  }

  // 1. Save User Prompt
  try {
    const qSaveUser = `
      INSERT INTO Messages (conversation_id, user_matricule, role, content)
      VALUES (?, ?, 'User', ?)
    `;
    await query(qSaveUser, [conversationId, userMatricule, message]);

    // Log chat interaction
    await logActivity("CHAT_MESSAGE_SENT", {
      ticketId,
      userMatricule,
      details: { message: `User sent message: ${message.slice(0, 50)}...` }
    });

  } catch (err) {
    console.error("Failed to save user chat:", err);
  }

  const reply = await getGostChatResponse(message, history);

  // 2. Save AI Reply
  try {
    const qSaveAI = `
      INSERT INTO Messages (conversation_id, user_matricule, role, content)
      VALUES (?, 'SYSTEM', 'AI', ?)
    `;
    await query(qSaveAI, [conversationId, reply]);

    // Log AI reply
    await query(
      "INSERT INTO audit_logs (user_matricule, action, details) VALUES (?, ?, ?)",
      ["SYSTEM", "CHAT_MESSAGE_REPLIED", JSON.stringify({ message: `AI replied for ticket ${ticketId}` })]
    );

  } catch (err) {
    console.error("Failed to save AI chat:", err);
  }

  return JSON.parse(JSON.stringify(reply));
}

export async function getChatMessagesForTicketAction(ticketId: string): Promise<ChatMessage[]> {
  const q = `
    SELECT m.id, m.conversation_id as conversationId, m.role, m.content, m.created_at as createdAt, m.user_matricule as senderName
    FROM Messages m
    JOIN Conversations c ON m.conversation_id = c.conversation_id
    WHERE c.ticket_id = ?
    ORDER BY m.created_at ASC
  `;
  const rows = await query<any>(q, [ticketId]);
  const data = rows.map((r: any) => ({
    id: r.id.toString(),
    conversationId: r.conversationId,
    ticketId: ticketId, // added for components relying on ticketId
    role: r.role,
    content: r.content,
    createdAt: r.createdAt,
    senderName: r.senderName || (r.role === 'AI' ? 'GOST AI' : 'Agent')
  }));
  return JSON.parse(JSON.stringify(data));
}

/**
 * Hard-deletes a conversation by its conversation_id.
 * The SQL DELETE on Conversations cascades to the Messages table
 * (FK ON DELETE CASCADE), so all child messages are removed atomically.
 *
 * After deletion the /chat history route is revalidated so the
 * sidebar immediately reflects the change on next render.
 */
export async function deleteConversationAction(conversationId: string) {
  const session = await getSession();
  const userMatricule = session.user?.matricule || "UNKNOWN";

  // Fetch conversation metadata before deletion for audit logging
  const convRows = await query<any>(
    "SELECT conversation_id, ticket_id FROM Conversations WHERE conversation_id = ?",
    [conversationId]
  );

  if (convRows.length === 0) {
    return { success: false, error: "Conversation not found" };
  }

  const ticketId = convRows[0].ticket_id;

  // Hard-delete: CASCADE will remove all Messages rows automatically
  await query("DELETE FROM Conversations WHERE conversation_id = ?", [conversationId]);

  // Audit trail
  await query(
    "INSERT INTO audit_logs (user_matricule, action, details) VALUES (?, ?, ?)",
    [
      userMatricule,
      "DELETE_CONVERSATION",
      JSON.stringify({
        message: `Hard-deleted conversation ${conversationId} (ticket ${ticketId})`,
        conversationId,
        ticketId,
      }),
    ]
  );

  // Revalidate both the history list and the specific ticket chat page
  revalidatePath("/chat");
  revalidatePath(`/chat/${ticketId}`);

  return { success: true };
}

export async function validateAnalysisAction(ticketId: string) {
  const session = await getSession();
  const userMatricule = session.user?.matricule || "UNKNOWN";

  // 0. Pre-flight checks (outside transaction – read-only)
  const [ticket] = await query<any>("SELECT state, description FROM tickets WHERE number = ?", [ticketId]);
  if (!ticket) return { success: false, error: "Ticket not found" };
  if (ticket.state === 'Validated' || ticket.state?.toLowerCase() === 'validated') {
    return { success: false, error: "Ticket is already validated" };
  }

  // 1. Get existing analysis
  const [analysis] = await query<any>("SELECT * FROM ai_analysis WHERE incident_number = ?", [ticketId]);
  if (!analysis) return { success: false, error: "Analysis not found. Run AI analysis first." };

  // Ensure analysis_id exists; generate one if it was created before migration
  let analysisId = analysis.analysis_id;
  if (!analysisId) {
    analysisId = generateId("ANALYSIS");
    await execute("UPDATE ai_analysis SET analysis_id = ? WHERE incident_number = ?", [analysisId, ticketId]);
  }

  // 2. Transactional commit – both validated_incidents and ticket state update
  //    are committed atomically. If any step fails, everything rolls back.
  try {
    await transaction(async (conn) => {
      // 2a. Insert validated incident with analysis_id FK
      await conn.execute(`
        INSERT INTO validated_incidents (incident_number, validated_by, incident_description, target_table, final_solution, analysis_id)
        VALUES (?, ?, ?, ?, ?, ?)
        ON DUPLICATE KEY UPDATE
          validated_by = VALUES(validated_by),
          incident_description = VALUES(incident_description),
          final_solution = VALUES(final_solution),
          analysis_id = VALUES(analysis_id)
      `, [
        ticketId,
        userMatricule,
        ticket.description || '',
        '', // target_table – populated if known
        analysis.resolution_steps || '',
        analysisId
      ]);

      // 2b. Update ticket state
      await conn.execute("UPDATE tickets SET state = 'Validated', comments = ? WHERE number = ?", [
        `AI solution validated by ${userMatricule}. Analysis ID: ${analysisId}. Solution: ${analysis.resolution_steps}`,
        ticketId
      ]);

      // 2c. Audit log
      await logActivity("TICKET_VALIDATED", {
        ticketId,
        userMatricule,
        details: { message: `Validated AI analysis for ticket ${ticketId}`, analysisId }
      });
    });
  } catch (err) {
    console.error("[validateAnalysisAction] Transaction failed:", err);
    return { success: false, error: "Validation transaction failed. No data was committed." };
  }

  return { success: true, analysisId };
}

export async function rejectAnalysisAction(ticketId: string, reason: string = "") {
  const session = await getSession();
  const userMatricule = session.user?.matricule || "UNKNOWN";

  await query("UPDATE tickets SET state = 'Rejected', comments = ? WHERE number = ?", [
    `AI solution rejected by ${userMatricule}. Reason: ${reason}`,
    ticketId
  ]);

  await logActivity("TICKET_REJECTED", {
    ticketId,
    userMatricule,
    details: { message: `Rejected AI analysis for ticket ${ticketId}`, reason }
  });

  return { success: true };
}

export async function cleanupOldDataAction() {
  // 30 days ago
  const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().slice(0, 19).replace('T', ' ');
  
  // Delete old conversations
  await query("DELETE FROM Conversations WHERE created_at < ?", [thirtyDaysAgo]);
  
  // Delete old sessions
  await query("DELETE FROM sessions WHERE expires_at < NOW()");
  
  return { success: true };
}

/**
 * Logs a SQL execution event. 
 * This is called from the UI when a user runs a suggested or manual query.
 */
export async function logSqlExecutionAction(ticketId: string, sql: string, status: "success" | "error" = "success") {
  return await logActivity("SQL_EXECUTED", {
    ticketId,
    details: { 
      query: sql, 
      status,
      message: `Executed SQL for ticket ${ticketId}`
    }
  });
}
